name: CI/CD
on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install FastAPI dependencies
      run: |
        cd backend
        pip install fastapi uvicorn pytest
    - name: Run backend tests
      run: |
        cd backend
        pytest
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install and test frontend
      run: |
        cd frontend
        npm install
        npm run test
    - name: Docker build and push (placeholder)
      run: echo "Docker build and push would be here"